name: 'Build-Test-MSDeploy'
description: 'Build Test and Deploy the project right after reviewing and merging PR into the master branch using msdeploy to your hosted IIS Server Site'

inputs: 
  PROJECT_DIRECOTRY_NAME:
    description: '.NET project directory which needs to be published over the IIS Server Site'
  PROJECT_CSPROJ_FILE_PATH:
    description: '.NET project file path for .csproj file'
    required: false
    
runs:
  using: 'docker'
  main: 'Dockerfile'
  
  branding:
  icon: "aperture"
  color: "purple"
