name: 'Build-Test-MSDeploy'
description: 'Build Test and Deploy the project right after reviewing and merging PR into the master branch using msdeploy to your hosted IIS Server Site.'

branding:
  icon: "aperture"
  color: "purple"
  
runs:
  using: 'docker'
  image: 'Dockerfile'
