name: 'Build-Test-MSDeploy'
description: 'Build Test and Deploy the project using msdeploy to your hosted IIS Server Site.'

branding:
  icon: "aperture"
  color: "purple"
  
runs:
  using: 'node12'
  main: 'index.js'
