name: 'Build-Test-MSDeploy'
description: 'Build Test and Deploy the project right after reviewing and merging PR into the master branch using msdeploy to your hosted IIS Server Site.'

branding:
  icon: "aperture"
  color: "purple"

jobs:

  Build-Test-Deploy:
    runs-on: windows-latest
    env:
      PROJECT_DIRECTORY_PATH: "TestGithubActions"

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Build with dotnet
      run: dotnet publish
           ${{ env.PROJECT_DIRECTORY_PATH }}/${{ env.PROJECT_DIRECTORY_PATH }}.csproj
           --source https://api.nuget.org/v3/index.json
           --configuration Release
           
    - name: Test with dotnet
      run: dotnet test
    